# Generated by Django 2.2 on 2023-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_Vlad', '0002_alter_noteform_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteform',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
