# Generated by Django 4.1.5 on 2023-01-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes_Vlad", "0004_alter_noteform_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoteForm",
            new_name="NoteModel",
        ),
    ]
