# Generated by Django 4.1.5 on 2023-01-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes_Vlad", "0007_alter_notemodel_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notemodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="notes_Vlad.category",
            ),
        ),
    ]
