# Generated by Django 4.1.5 on 2023-01-11 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_Vlad", "0008_alter_notemodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="notemodel",
            name="time_add",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
