# Generated by Django 4.1.5 on 2023-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_Vlad", "0012_alter_notemodel_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notemodel",
            name="content",
            field=models.CharField(max_length=80, verbose_name="Заметка"),
        ),
    ]
